"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/table";
import { useAuth } from "@/contexts/AuthContext";
import { apiUrl } from "@/lib/api";

type SettlementReport = {
  id: string;
  report_date: string;
  escrow_inflow: string | number;
  released_to_students: string | number;
  refunded_to_companies: string | number;
  withdrawals: string | number;
  platform_fees: string | number;
  system_available_total: string | number;
  system_escrow_total: string | number;
  created_at: string;
};

type SettlementResponse = {
  pagination: {
    limit: number;
    offset: number;
    total: number;
  };
  totals: {
    escrow_inflow: string | number;
    released_to_students: string | number;
    refunded_to_companies: string | number;
    withdrawals: string | number;
    platform_fees: string | number;
  };
  reports: SettlementReport[];
};

const DEFAULT_LIMIT = 50;

export default function SettlementsPage() {
  const { authHeaders, isAuthenticated, isLoading: authLoading } = useAuth();
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");
  const [activeFromDate, setActiveFromDate] = useState("");
  const [activeToDate, setActiveToDate] = useState("");
  const [offset, setOffset] = useState(0);
  const [data, setData] = useState<SettlementResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const queryString = useMemo(() => {
    const params = new URLSearchParams();
    params.set("limit", String(DEFAULT_LIMIT));
    params.set("offset", String(offset));
    if (activeFromDate) params.set("from", activeFromDate);
    if (activeToDate) params.set("to", activeToDate);
    return params.toString();
  }, [activeFromDate, activeToDate, offset]);

  const fetchReports = useCallback(async () => {
    if (!isAuthenticated) return;

    setLoading(true);
    try {
      const res = await fetch(apiUrl(`/api/admin/reports/settlements?${queryString}`), {
        headers: authHeaders(),
      });
      if (!res.ok) {
        const body = await res.json().catch(() => null);
        throw new Error(body?.message || "Failed to fetch settlement reports");
      }

      const json: SettlementResponse = await res.json();
      setData(json);
      setError(null);
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : "Failed to load settlement reports";
      setError(message);
      setData(null);
    } finally {
      setLoading(false);
    }
  }, [authHeaders, isAuthenticated, queryString]);

  useEffect(() => {
    if (!authLoading) {
      if (isAuthenticated) {
        fetchReports();
      } else {
        setLoading(false);
      }
    }
  }, [authLoading, fetchReports, isAuthenticated]);

  const onApplyFilters = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setOffset(0);
    setActiveFromDate(fromDate);
    setActiveToDate(toDate);
  };

  const onResetFilters = () => {
    setFromDate("");
    setToDate("");
    setActiveFromDate("");
    setActiveToDate("");
    setOffset(0);
  };

  const total = data?.pagination.total ?? 0;
  const hasPrev = offset > 0;
  const hasNext = offset + DEFAULT_LIMIT < total;

  if (authLoading) return <div className="p-10">Loading authentication...</div>;
  if (!isAuthenticated)
    return <div className="p-10">Please log in to view settlement reports.</div>;

  return (
    <div className="container mx-auto py-10 space-y-6">
      <div>
        <h1 className="text-2xl font-bold">Settlement Reports</h1>
        <p className="text-sm text-gray-600">
          Daily finance snapshots generated by the settlement engine.
        </p>
      </div>

      <form onSubmit={onApplyFilters} className="bg-white border rounded p-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          <input
            type="date"
            className="border rounded px-3 py-2"
            value={fromDate}
            onChange={(e) => setFromDate(e.target.value)}
          />
          <input
            type="date"
            className="border rounded px-3 py-2"
            value={toDate}
            onChange={(e) => setToDate(e.target.value)}
          />
        </div>
        <div className="flex gap-2 mt-4">
          <button
            type="submit"
            className="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700"
          >
            Apply filters
          </button>
          <button
            type="button"
            className="bg-gray-200 text-gray-800 px-4 py-2 rounded hover:bg-gray-300"
            onClick={onResetFilters}
          >
            Reset
          </button>
        </div>
      </form>

      {loading ? (
        <div>Loading settlement reports...</div>
      ) : error ? (
        <div className="text-red-500">{error}</div>
      ) : data ? (
        <>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-3">
            <SummaryCard title="Escrow Inflow" value={data.totals.escrow_inflow} />
            <SummaryCard
              title="Released to Students"
              value={data.totals.released_to_students}
            />
            <SummaryCard
              title="Refunded to Companies"
              value={data.totals.refunded_to_companies}
            />
            <SummaryCard title="Withdrawals" value={data.totals.withdrawals} />
            <SummaryCard title="Platform Fees" value={data.totals.platform_fees} />
          </div>

          <Table>
            <TableCaption>Generated daily at 2:05 AM server time.</TableCaption>
            <TableHeader>
              <TableRow>
                <TableHead>Report Date</TableHead>
                <TableHead>Escrow Inflow</TableHead>
                <TableHead>Released</TableHead>
                <TableHead>Refunded</TableHead>
                <TableHead>Withdrawals</TableHead>
                <TableHead>Platform Fees</TableHead>
                <TableHead>System Available</TableHead>
                <TableHead>System Escrow</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {data.reports.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={8} className="text-center">
                    No settlement reports found.
                  </TableCell>
                </TableRow>
              ) : (
                data.reports.map((report) => (
                  <TableRow key={report.id}>
                    <TableCell>{new Date(report.report_date).toLocaleDateString()}</TableCell>
                    <TableCell>{formatNaira(report.escrow_inflow)}</TableCell>
                    <TableCell>{formatNaira(report.released_to_students)}</TableCell>
                    <TableCell>{formatNaira(report.refunded_to_companies)}</TableCell>
                    <TableCell>{formatNaira(report.withdrawals)}</TableCell>
                    <TableCell>{formatNaira(report.platform_fees)}</TableCell>
                    <TableCell>{formatNaira(report.system_available_total)}</TableCell>
                    <TableCell>{formatNaira(report.system_escrow_total)}</TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>

          <div className="flex justify-end gap-2">
            <button
              className="px-3 py-2 rounded border disabled:opacity-50"
              onClick={() => setOffset((prev) => Math.max(prev - DEFAULT_LIMIT, 0))}
              disabled={!hasPrev}
            >
              Previous
            </button>
            <button
              className="px-3 py-2 rounded border disabled:opacity-50"
              onClick={() => setOffset((prev) => prev + DEFAULT_LIMIT)}
              disabled={!hasNext}
            >
              Next
            </button>
          </div>
        </>
      ) : null}
    </div>
  );
}

function SummaryCard({ title, value }: { title: string; value: string | number }) {
  return (
    <div className="bg-white border rounded p-4">
      <div className="text-sm text-gray-500">{title}</div>
      <div className="text-xl font-bold">{formatNaira(value)}</div>
    </div>
  );
}

function formatNaira(value: string | number) {
  const num = Number(value);
  if (!Number.isFinite(num)) return String(value);
  return `₦${num.toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}
